spring:
  application:
    name: courier-service
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8083


twilio: 
    account_sid: <Sid>
    auth_token: <Token>
    trial_number: <Number>

springdoc:
  swagger-ui:
    path: /swagger-ui.html